# Generated by Django 6.0.3 on 2025-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_uploadedimage_delete_uploadedimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
