# Generated by Django 6.0.3 on 2025-11-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_uploadedimage_owner_uploadedimage_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='owner',
        ),
    ]
