# Generated by Django 6.0.3 on 2025-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_uploadedimage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='premium',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='Business_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
